#!/bin/sh

if [ "$#" -eq "0" ]
  then
    echo "Usage: $0 YOUR-MNT"
    exit
fi

BASE="$(readlink -f "$0" 2>/dev/null || python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$0")"
BASE="$(dirname "$BASE")"

grep -lrE "(\s|:)$1(\s|\$)" "$BASE/data/" | while read -r line; do
    utils/schema-check/tripnet-schema.py fmt -i "$line"
done

